### ISSUE TITLE
Changes suggested in the README do not trigger a build

### ISSUE THREAD

**Issue by elenalape** [digitalocean/sample-react#6]
I cloned the repo and deployed the app as is, which worked fine. However, then I tried making two changes to the app, deploying after each:

1. Edited `src/App.js` (https://github.com/elenalape/sample-react/commit/349801f158e9de81d49b828bcd41700da4d77a76)
2. Edited `public/index.html`, as is suggested in this repo's README (https://github.com/elenalape/sample-react/commit/1eebdbf3e6ab5cf87e337a28d847a44a5e9251a4)

Neither of those seemed to have triggered a re-build, so it just deploys the app with no changes, i.e. in the Dashboard under `Deployments` it says 

> **Build logs**
>
> The build was skipped for this deployment.

Upon consulting the[ docs](https://www.digitalocean.com/docs/app-platform/how-to/troubleshoot-app/#if-the-build-was-skipped-consult-earlier-logs) about this, I can't find a simple solution.

**Comment by kamaln7** [comment]
👋🏼  @elenalape 

Sorry for the late response. This is a little strange, these changes should have definitely triggered a rebuild. My guess is that the `master` branch was used for the app but the commits were made to the `main` branch—I ran into this myself before and it's easy to miss. If that's not the case, please open a support ticket and we'll look into what's happening!

I'm closing the issue but please feel free to re-open it.

Also, please post any questions or issues you run into [on the DigitalOcean Q&A](https://www.digitalocean.com/community/questions/new?tags=Digitalocean%20App%20Platform). The team closely monitors that and you should get a much quicker response than here 😄
